### ISSUE TITLE
Release gem

### ISSUE THREAD

**Issue by aaronchi** [jjbohn/omniauth-openid-connect#30]
It looks like the version was bumped to 0.2.0 recently but no gem was released. Can we get a new release to rubygems?

**Comment by stormsilver** [comment]
:+1:  on this, seems like there has been a ton of activity on the project but no release to rubygems in a year?

**Comment by tonycchung** [comment]
Also :+1: 

Currently just using :git => "git@github.com:jjbohn/omniauth-openid-connect.git" for now. Actually forked my own version and made some small changes and pointing to that but yeah. Didn't realize I was using 0.1.0 and couldn't figure out why I was having issues in picking up the raw_attributes of the payload.

**Comment by odigity** [comment]
I just checked, and counted 67 commits since the last release -- out of 105 total.  More commits have happened since the last release than all commits total before the last release.  :)

Would really like to see another release soon...

**Comment by aaronchi** [comment]
Did you really count all of them? I'm impressed.

**Comment by jjbohn** [comment]
Hey all,
Just release 0.2.1 and push up to rubygems. Sorry for the big delay with the project. I didn't get notifications for a long time. At the same time, I haven't actually used the gem for over a year and a half so I usually don't have the gem top of mind.

**Comment by odigity** [comment]
Thanks for doing that!
