### ISSUE TITLE
Support openid-connect 0.9.2 and newer JWT library version

### ISSUE THREAD

**Issue by tanelsuurhans** [jjbohn/omniauth-openid-connect#37]
https://github.com/nov/openid_connect was recently updated, would there be a chance of updating this gem to bump the dependency versions?

**Comment by odigity** [comment]
+1

I could modify the .gemspec myself, but the real question is:

Is there a reason the .gemspec pegs openid_connect at 0.7.3?  Are there breaking changes that happened after that release?

**Comment by jjbohn** [comment]
This should be resolved with #40 now.

**Comment by odigity** [comment]
Will v0.2.1 get pushed to rubygems?  (Last release was 0.1.0 in Mar 2014.)

**Comment by jjbohn** [comment]
@odigity just pushed to ruby gems. Thanks!

**Comment by odigity** [comment]
Awesome!
