### ISSUE TITLE
expose parsed id_token

### ISSUE THREAD

**Issue by singpolyma** [jjbohn/omniauth-openid-connect#48]
So that one can actually get at the `sub` needed to identify a user

**Comment by hotgazpacho** [comment]
Take a look at the [`uid`](https://github.com/jjbohn/omniauth-openid-connect/blob/master/lib/omniauth/strategies/openid_connect.rb#L46) that the strategy exposes in the auth hash. Seems this comes from the `sub` claim on the access token. I would hope that these would be the same on both the ID token and Access token...

**Comment by singpolyma** [comment]
I no longer have access to the project I was doing this for.  Will check out if this works if I ever have need again.
